// Symptom dictionary from the Python code
export const symptoms_dict: Record<string, number> = {
  itching: 0,
  skin_rash: 1,
  nodal_skin_eruptions: 2,
  continuous_sneezing: 3,
  shivering: 4,
  chills: 5,
  joint_pain: 6,
  stomach_pain: 7,
  acidity: 8,
  ulcers_on_tongue: 9,
  muscle_wasting: 10,
  vomiting: 11,
  burning_micturition: 12,
  spotting_urination: 13,
  fatigue: 14,
  weight_gain: 15,
  anxiety: 16,
  cold_hands_and_feets: 17,
  mood_swings: 18,
  weight_loss: 19,
  restlessness: 20,
  lethargy: 21,
  patches_in_throat: 22,
  irregular_sugar_level: 23,
  cough: 24,
  high_fever: 25,
  sunken_eyes: 26,
  breathlessness: 27,
  sweating: 28,
  dehydration: 29,
  indigestion: 30,
  headache: 31,
  yellowish_skin: 32,
  dark_urine: 33,
  nausea: 34,
  loss_of_appetite: 35,
  pain_behind_the_eyes: 36,
  back_pain: 37,
  constipation: 38,
  abdominal_pain: 39,
  diarrhoea: 40,
  mild_fever: 41,
  yellow_urine: 42,
  yellowing_of_eyes: 43,
  acute_liver_failure: 44,
  fluid_overload: 45,
  swelling_of_stomach: 46,
  swelled_lymph_nodes: 47,
  malaise: 48,
  blurred_and_distorted_vision: 49,
  phlegm: 50,
  throat_irritation: 51,
  redness_of_eyes: 52,
  sinus_pressure: 53,
  runny_nose: 54,
  congestion: 55,
  chest_pain: 56,
  weakness_in_limbs: 57,
  fast_heart_rate: 58,
  pain_during_bowel_movements: 59,
  pain_in_anal_region: 60,
  bloody_stool: 61,
  irritation_in_anus: 62,
  neck_pain: 63,
  dizziness: 64,
  cramps: 65,
  bruising: 66,
  obesity: 67,
  swollen_legs: 68,
  swollen_blood_vessels: 69,
  puffy_face_and_eyes: 66,
  obesity: 67,
  swollen_legs: 68,
  swollen_blood_vessels: 69,
  puffy_face_and_eyes: 70,
  enlarged_thyroid: 71,
  brittle_nails: 72,
  swollen_extremeties: 73,
  excessive_hunger: 74,
  extra_marital_contacts: 75,
  drying_and_tingling_lips: 76,
  slurred_speech: 77,
  knee_pain: 78,
  hip_joint_pain: 79,
  muscle_weakness: 80,
  stiff_neck: 81,
  swelling_joints: 82,
  movement_stiffness: 83,
  spinning_movements: 84,
  loss_of_balance: 85,
  unsteadiness: 86,
  weakness_of_one_body_side: 87,
  loss_of_smell: 88,
  bladder_discomfort: 89,
  foul_smell_of_urine: 90,
  continuous_feel_of_urine: 91,
  passage_of_gases: 92,
  internal_itching: 93,
  toxic_look_typhos: 94,
  depression: 95,
  irritability: 96,
  muscle_pain: 97,
  altered_sensorium: 98,
  red_spots_over_body: 99,
  belly_pain: 100,
  abnormal_menstruation: 101,
  dischromic_patches: 102,
  watering_from_eyes: 103,
  increased_appetite: 104,
  polyuria: 105,
  family_history: 106,
  mucoid_sputum: 107,
  rusty_sputum: 108,
  lack_of_concentration: 109,
  visual_disturbances: 110,
  receiving_blood_transfusion: 111,
  receiving_unsterile_injections: 112,
  coma: 113,
  stomach_bleeding: 114,
  distention_of_abdomen: 115,
  history_of_alcohol_consumption: 116,
  fluid_overload: 117,
  blood_in_sputum: 118,
  prominent_veins_on_calf: 119,
  palpitations: 120,
  painful_walking: 121,
  pus_filled_pimples: 122,
  blackheads: 123,
  scurring: 124,
  skin_peeling: 125,
  silver_like_dusting: 126,
  small_dents_in_nails: 127,
  inflammatory_nails: 128,
  blister: 129,
  red_sore_around_nose: 130,
  yellow_crust_ooze: 131,
}

// List of all symptoms for the dropdown
export const symptoms = Object.keys(symptoms_dict)

// Disease list from the Python code
export const diseases_list: Record<number, string> = {
  15: "Fungal infection",
  4: "Allergy",
  16: "GERD",
  9: "Chronic cholestasis",
  14: "Drug Reaction",
  33: "Peptic ulcer diseae",
  1: "AIDS",
  12: "Diabetes",
  17: "Gastroenteritis",
  6: "Bronchial Asthma",
  23: "Hypertension",
  30: "Migraine",
  7: "Cervical spondylosis",
  32: "Paralysis (brain hemorrhage)",
  28: "Jaundice",
  29: "Malaria",
  8: "Chicken pox",
  11: "Dengue",
  37: "Typhoid",
  40: "Hepatitis A",
  19: "Hepatitis B",
  20: "Hepatitis C",
  21: "Hepatitis D",
  22: "Hepatitis E",
  3: "Alcoholic hepatitis",
  36: "Tuberculosis",
  10: "Common Cold",
  34: "Pneumonia",
  13: "Dimorphic hemmorhoids(piles)",
  18: "Heart attack",
  39: "Varicose veins",
  26: "Hypothyroidism",
  24: "Hyperthyroidism",
  25: "Hypoglycemia",
  31: "Osteoarthristis",
  5: "Arthritis",
  0: "(vertigo) Paroymsal Positional Vertigo",
  2: "Acne",
  38: "Urinary tract infection",
  35: "Psoriasis",
  27: "Impetigo",
}

// Sample database of disease information
const diseaseDatabase = {
  "Fungal infection": {
    description:
      "A fungal infection is a condition where fungi invade and grow on or in the human body, causing irritation and inflammation. Common types include athlete's foot, ringworm, and candidiasis.",
    precautions: [
      "Keep the affected area clean and dry",
      "Avoid sharing personal items",
      "Use antifungal medications as prescribed",
      "Maintain good hygiene",
    ],
    medications: ["Clotrimazole", "Miconazole", "Terbinafine", "Fluconazole"],
    workout: [
      "Light exercises if not contraindicated",
      "Avoid excessive sweating in affected areas",
      "Wear loose, breathable clothing during exercise",
    ],
    diet: ["Probiotic-rich foods", "Low-sugar diet", "Garlic and other antifungal foods", "Stay hydrated"],
    commonSymptoms: ["itching", "skin_rash", "nodal_skin_eruptions", "dischromic_patches"],
  },
  Allergy: {
    description:
      "An allergy is an immune system response to a foreign substance that's not typically harmful to your body. These foreign substances are called allergens and can include certain foods, pollen, or pet dander.",
    precautions: [
      "Identify and avoid allergens",
      "Keep emergency medication on hand if prescribed",
      "Wear medical alert bracelet if severe",
      "Create an allergy action plan",
    ],
    medications: ["Antihistamines", "Decongestants", "Corticosteroids", "Epinephrine (for severe reactions)"],
    workout: [
      "Indoor exercises during high pollen seasons",
      "Swimming in clean, well-maintained pools",
      "Avoid exercising in cold, dry air if sensitive",
    ],
    diet: [
      "Avoid known food allergens",
      "Anti-inflammatory foods",
      "Foods rich in quercetin (onions, apples)",
      "Omega-3 rich foods",
    ],
    commonSymptoms: ["continuous_sneezing", "shivering", "chills", "watering_from_eyes"],
  },
  GERD: {
    description:
      "Gastroesophageal reflux disease (GERD) is a chronic digestive disease that occurs when stomach acid or bile flows back into the food pipe and irritates the lining. This backwash (reflux) can irritate the lining of your esophagus.",
    precautions: [
      "Avoid lying down after eating",
      "Elevate the head of your bed",
      "Maintain a healthy weight",
      "Avoid trigger foods and drinks",
    ],
    medications: ["Antacids", "H-2-receptor blockers", "Proton pump inhibitors", "Prokinetics"],
    workout: [
      "Low-impact exercises",
      "Avoid exercises that increase abdominal pressure",
      "Wait 2-3 hours after eating before exercising",
      "Stay upright during and after exercise",
    ],
    diet: [
      "Avoid spicy, fatty foods",
      "Limit caffeine and alcohol",
      "Eat smaller, more frequent meals",
      "Avoid eating close to bedtime",
    ],
    commonSymptoms: ["stomach_pain", "acidity", "ulcers_on_tongue", "vomiting", "indigestion", "chest_pain"],
  },
  "Common Cold": {
    description:
      "The common cold is a viral infection of your nose and throat (upper respiratory tract). It's usually harmless, although it might not feel that way. Many types of viruses can cause a common cold.",
    precautions: [
      "Wash hands frequently",
      "Avoid close contact with sick people",
      "Rest and stay hydrated",
      "Disinfect frequently touched surfaces",
    ],
    medications: ["Decongestants", "Pain relievers", "Cough suppressants", "Antihistamines"],
    workout: [
      "Rest during acute symptoms",
      "Light walking when feeling better",
      "Gentle stretching",
      "Resume normal activity gradually",
    ],
    diet: ["Chicken soup", "Hot tea with honey", "Citrus fruits and berries", "Stay well hydrated"],
    commonSymptoms: [
      "continuous_sneezing",
      "chills",
      "fatigue",
      "cough",
      "high_fever",
      "headache",
      "swelled_lymph_nodes",
      "malaise",
      "phlegm",
      "throat_irritation",
      "redness_of_eyes",
      "sinus_pressure",
      "runny_nose",
      "congestion",
      "loss_of_smell",
    ],
  },
  Diabetes: {
    description:
      "Diabetes is a disease that occurs when your blood glucose, also called blood sugar, is too high. Blood glucose is your main source of energy and comes from the food you eat. Insulin, a hormone made by the pancreas, helps glucose get into your cells to be used for energy.",
    precautions: [
      "Monitor blood sugar regularly",
      "Take medications as prescribed",
      "Follow a balanced diet plan",
      "Regular physical activity",
    ],
    medications: ["Insulin", "Metformin", "Sulfonylureas", "DPP-4 inhibitors"],
    workout: ["Regular aerobic exercise", "Strength training", "Flexibility exercises", "Balance training"],
    diet: ["Low glycemic index foods", "High fiber foods", "Lean proteins", "Limited refined carbs and sugars"],
    commonSymptoms: [
      "fatigue",
      "weight_loss",
      "restlessness",
      "lethargy",
      "irregular_sugar_level",
      "excessive_hunger",
      "increased_appetite",
      "polyuria",
    ],
  },
  Malaria: {
    description:
      "Malaria is a serious and sometimes fatal disease caused by a parasite that commonly infects a certain type of mosquito which feeds on humans. People who get malaria are typically very sick with high fevers, shaking chills, and flu-like illness.",
    precautions: [
      "Use mosquito repellent",
      "Sleep under mosquito nets",
      "Wear long-sleeved clothing",
      "Take antimalarial drugs when traveling to endemic areas",
    ],
    medications: ["Chloroquine", "Artemisinin-based combination therapies", "Atovaquone-proguanil", "Mefloquine"],
    workout: [
      "Rest during acute illness",
      "Gentle activity during recovery",
      "Gradually increase exercise as strength returns",
      "Stay hydrated",
    ],
    diet: ["Hydrating fluids", "Easily digestible foods", "Nutrient-rich diet during recovery", "Foods high in iron"],
    commonSymptoms: ["chills", "vomiting", "high_fever", "sweating", "headache", "nausea", "muscle_pain", "diarrhoea"],
  },
  Pneumonia: {
    description:
      "Pneumonia is an infection that inflames the air sacs in one or both lungs. The air sacs may fill with fluid or pus, causing cough with phlegm or pus, fever, chills, and difficulty breathing.",
    precautions: ["Get vaccinated", "Practice good hygiene", "Don't smoke", "Keep your immune system strong"],
    medications: ["Antibiotics", "Cough medicine", "Fever reducers/pain relievers", "Bronchodilators"],
    workout: [
      "Complete rest during acute phase",
      "Breathing exercises",
      "Gradual return to activity",
      "Pulmonary rehabilitation if recommended",
    ],
    diet: ["Protein-rich foods", "Vitamin C rich foods", "Warm broths and soups", "Stay well hydrated"],
    commonSymptoms: [
      "chills",
      "fatigue",
      "cough",
      "high_fever",
      "breathlessness",
      "sweating",
      "chest_pain",
      "phlegm",
      "rusty_sputum",
    ],
  },
}

// Function to get disease information
export function getDiseaseInfo(diseaseName: string) {
  // Default values if disease not found
  const defaultInfo = {
    description: "No detailed information available for this condition.",
    precautions: [
      "Consult with a healthcare professional",
      "Follow prescribed treatment",
      "Monitor symptoms",
      "Maintain a healthy lifestyle",
    ],
    medications: ["Consult with a healthcare professional for appropriate medications"],
    workout: ["Consult with a healthcare professional before starting any exercise regimen"],
    diet: ["Maintain a balanced diet", "Stay hydrated", "Consult with a nutritionist for specific recommendations"],
  }

  // Return disease info if found, otherwise return default
  const diseaseInfo = diseaseDatabase[diseaseName as keyof typeof diseaseDatabase]

  if (diseaseInfo) {
    return {
      description: diseaseInfo.description,
      precautions: diseaseInfo.precautions,
      medications: diseaseInfo.medications,
      workout: diseaseInfo.workout,
      diet: diseaseInfo.diet,
    }
  }

  return defaultInfo
}

// Attach the database to the function for use in other functions
getDiseaseInfo.diseaseDatabase = diseaseDatabase

